<h1> Website Privacy Notice</h1>
	                

<h2>Purposes of Data Collection</h2>
<p>In order to improve our understanding of how researchers use the Manuscript Collection Database, we analyze anonymous weblog and transaction data related to the use of this website.</p>
<h2 >Collection and Usage of Anonymous Data</h2>
<p>When you use this website, anonymous transaction log data is automatically gathered from information sent to us by your browser. This information is stored in a secure server maintained by the Library.</p>
<p>In addition, persistent cookies may be created on your computer. Cookies are small pieces of data stored by a web browser on your computer, containing information that your browser submits to us. Anonymous data generated by the cookie about your use of the website (including your IP address) will be stored by the Library in a secure database and may also be transmitted to a third party ("<a href="http://www.google.com/analytics" onclick="_gaq.push(['_trackEvent', 'outbound-article', 'http://www.google.com/analytics', 'Google Analytics']);" >Google Analytics</a>"), where it is stored on servers in the United States.</p>
<p>The cookie allows us to gather and analyze summary information for the purpose of helping improve the quality of the information provided on this website.<a href="#footnote">[1]</a> We may report results of the summary data analysis at scholarly conferences and/or publication. There is no commercial use of the cookie and no other use of the cookie or the anonymous data generated by it beyond the terms outlined in this privacy notice.</p>
<p>The following types of anonymous data are collected internally and by Google Analytics:</p>
<ol>
<li>Internet address of computer or device accessing the website</li>
<li>Type of browser or other client application used</li>
<li>Display settings (such as screen resolution)</li>
<li>The operating system of the computer or device</li>
<li>Web pages requested</li>
<li>Referring Web pages</li>
<li>Times and dates of your request/time spent on the site</li>
</ol>
<h2>Refusing Cookies</h2>
<p>You may refuse the cookie by selecting the appropriate settings in your browser. If the cookie is refused, you will still be able to use our website, and anonymous data will still be collected in our internal transaction logs. However, no anonymous information will be transmitted to <a href="http://www.google.com/analytics" onclick="_gaq.push(['_trackEvent', 'outbound-article', 'http://www.google.com/analytics', 'Google Analytics']);" >Google Analytics</a>. By accepting cookies, you consent to the processing of data in the manner and for the purposes set out in this privacy notice.</p>
<h2>Further Information</h2>
<p>For more information about University Privacy Policies, please see the <a href="http://www.vpaa.uillinois.edu/policies/web_privacy.asp?bch=1" onclick="_gaq.push(['_trackEvent', 'outbound-article', 'http://www.vpaa.uillinois.edu/policies/web_privacy.asp?bch=1', 'University Privacy Policies page.']);" >University Privacy Policies page.</a></p>

<h2 id="footnote">Footnote</h2>
<p>[1] Google may transfer information to third parties where required to do so by law, or where such third parties process the information on Google&#8217;s behalf. Google will not associate your IP address with any other data held by Google. More information about Google&#8217;s privacy practices is available on their <a href="http://www.google.com/intl/en/privacy.html" onclick="_gaq.push(['_trackEvent', 'outbound-article', 'http://www.google.com/intl/en/privacy.html', 'privacy page.']);" >privacy page.</a></p>